### ISSUE TITLE
Prevent mod.json with conflicts from loading

### ISSUE THREAD

**Issue by LadyAlekto** [BattletechModders/ModTek#109]
Im trying to create a micromod that idiot proofs roguetech install a bit

I am trying this by creating a second landingscreen replacer that tells users to install the asset bundle

Problem is, it will not not load it once its present in the loadorder/cache even though the conflicting correct mod is present

**Comment by Mpstark** [comment]
I don't understand what the issue is, you're going to have to be more specific.

Conflicts work by not loading a mod when its conflict has already loaded. That's all they do.

**Comment by LadyAlekto** [comment]
Yeah but it also prevents loading the mods it has a conflict with

Basically it should not load the mod that has a conflict instead of the mods that are the conflict

Example

Mod1 has mod2 as conflict

Mod1 loads all fine normallly

But as soon as mod2 is present

it should switch of loading mod1
