### ISSUE TITLE
Merging or appending .csv files in itemCollections folder

### ISSUE THREAD

**Issue by griz1231** [BattletechModders/ModTek#117]
The .csv files int the itemCollections folder provide an easier method for modders to add their mechs and equipment into stores and salvage availability with rarity options rather than replacing entire arrays in the store json files and can be done as a merge/append operation the that won't interfere with other mods as readily. 

The csv files in the itemCollections directory are in a four column layout.
The first line of the file is the name of the collection.
subsequent lines are in the four column format.
Column 1 contains the name of the asset which may be the id of an item or the id of another collection.
column 2 is the type of asset.
	AmmunitionBox for ammo
	HeatSink for heatsinks
	JumpJet for jumpjets
	Upgrade for actuators, cockpit mods, gyros, TTS
	Weapon for weapons
	Mech for complete mechs
	MechPart for partial mechs
	Reference for other itemCollections
Column 3 is how many are available
	set to 0 for unlimited or an integer for other quantities
Column 4 is the chance an item will be available with 0 being never and 10 being always

**Comment by CptMoore** [comment]
Define new csv resource entries using the non--merge options and then merge starsystemdef jsons using advancedjson merge to avoid full array replacements.

However removing csv entries is not possible.

**Comment by griz1231** [comment]
Stores are as you state in your own documentation arrays which must be completely replaced in json merges. csv files are lists that can be appended or have individual entries modified without complete replacement. The point I am making is your method is equivalent to hard coding every upc code in a real store into their computer software instead of using a lookup table. HSB used the csv files to make adding items in stores in updates and dlc easier and you are fighting it doing it all in the json files. 

The itemCollections_Ammo_all.csv file especially, as this is where modders should be adding the ammo for new weapons to be available in stores. If everyone has to replace the whole file to add a new ammo type then only one mod can use the list at a time and everyone conflicts with each other. Your methods in the stores are brute force instead of finesse. The starsystemdef jsons don't need to be changed at all in those cases.

**Comment by CptMoore** [comment]
No I meant advanced json merges, you can append to arrays with those. See ArrayConcat part in https://github.com/BattletechModders/MechEngineer/blob/master/advancedjsonmerge/mechdef_atlas_AS7-D-HT.json .

**Comment by griz1231** [comment]
You should move that info to the modtek documentation then where it can be found by modtek users then

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by CptMoore** [comment]
Oh it is part of the readme, https://github.com/BattletechModders/ModTek/blob/master/README.md#advanced-json-merging

**Comment by Mpstark** [comment]
There is also an issue opened for updating documentation (#108) -- just need to do it.

**Comment by Mpstark** [comment]
PR #130 adds the ability to append text from CSV and TXT files with the manifest entry flag "ShouldAppendText" -- this flag is not set for the StreamingAssets implicit entry.
