### ISSUE TITLE
"ModTek Died!" error on v0.6.0/BT v1.4

### ISSUE THREAD

**Issue by Epssus** [BattletechModders/ModTek#121]
Whenever anything in the mod folder is changed, the first time trying to load the game, after ModTek loads, merges and pushes everything to the database, it quits and displays "Modtek died!". After killing the process for Battletech, the next load attempt seems to work just fine.

Modtek.log shows this error (which is gone on the second run:

`Uncaught ModTek exception!
Mono.Data.Sqlite.SqliteException: SQLite error
table MDD_DB.UnitDef has 6 columns but 8 values were supplied
  at Mono.Data.Sqlite.SQLite3.Prepare (Mono.Data.Sqlite.SqliteConnection cnn, System.String strSql, Mono.Data.Sqlite.SqliteStatement previous, UInt32 timeoutMS, System.String& strRemain) [0x00000] in <filename unknown>:0 
  at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand () [0x00000] in <filename unknown>:0 `

**Comment by Mpstark** [comment]
This sounds like a corrupted/non-upgraded MDDB -- are there any errors in output_log.txt? I'd be curious if everything is working fine now, or if anyone else has gotten this error.

**Comment by Epssus** [comment]
I upgraded to 0.6.1, and deleted my cache and database folders in .modtek, and so far it seems to have solved the issue.
