### ISSUE TITLE
Support for CustomResources

### ISSUE THREAD

**Issue by CptMoore** [BattletechModders/ModTek#122]
In CustomComponents and MechEngineer, ME is adding new configuration entries to CC using static public methods of CC.

Since the base game is configured using json resources anyway (weapons, mechs), mods should have the ability to add custom resources that are handled similar to base game resources. Loading should also be done without a hard dll reference between mods.

The current solution direction discussed on discord is
> ok, just a recap, register custom resource type in mod.json, any mod can then define resources of that type in their mod.json, and jsonmerging can apply. then mods can have a ModsLoaded method that ModTek will call once all mods were loaded including the resources merging. That ModLoaded will be given a dictionary of lists for all custom resource types containing all custom resources paths. something like that ~?~ !

Removal of resources would be appreciated but not necessary yet, see #38

**Comment by Mpstark** [comment]
I've got a working prototype in feature branch merged into develop -- I had to do some major cleanup surgery that was a little overdue as well because things were getting very cluttered in ModTek.cs.

**Comment by CptMoore** [comment]
Cool, Ive looked through the api and that should do it, going to switch MechEngineer to it as en example

**Comment by Mpstark** [comment]
ID is first looked for in the JSON, but if nothing found then it defaults to file name without the extension.

**Comment by Mpstark** [comment]
A note, as well, mods will only get the resources that they ask for in their mod.json.

**Comment by CptMoore** [comment]
ok, I'm using it with MechEngineer and CustomComponents and it works without issues

CC registers categories type, ME adds categories, CC processes them
