### ISSUE TITLE
After todays Battletech update, unhandled exception

### ISSUE THREAD

**Issue by BertMechman** [BattletechModders/ModTek#134]
Cached merge: turretdef_Standard_Sniper.json (3/12/2019 11:12:05 AM)
	BattleTech_Data\StreamingAssets\data\turrets\turretdef_Standard_Sniper.json
	Mods\XAI Battletech\StreamingAssets\data\turrets\turretdef_Standard_Sniper.json

	Add/Replace: ".modtek\Cache\BattleTech_Data\StreamingAssets\data\turrets\turretdef_Standard_Sniper.json" (TurretDef)

Uncaught ModTek exception!
System.MissingMethodException: Method not found: 'BattleTech.Data.MetadataDatabase.WriteInMemoryDBToDisk'.
  at ModTek.UI.ProgressPanel+ProgressBarLoadingBehavior+<RunWorkList>d__20.MoveNext () [0x00000] in <filename unknown>:0 

2:22:22 PM - Done. Elapsed running time: 11.7301406 seconds

Tried new installs of both battletech and modtek with no change.

**Comment by troysjanda** [comment]
I am also having the same error after upgrading to 1.5 I tried a reinstall or game and mods and modtech. did not resolve issue

**Comment by tmferretti** [comment]
Im encountering this issue as well

```
ModTek v0.7.0 -- 3/12/2019 10:00:02 PM
Building new config.
NOT PATCHING UnityGameInstance.ShutdownGame, game version is after 1.5.0
No ModTek-compatible mods found.

Uncaught ModTek exception!
System.MissingMethodException: Method not found: 'BattleTech.Data.MetadataDatabase.WriteInMemoryDBToDisk'.
  at ModTek.UI.ProgressPanel+ProgressBarLoadingBehavior+<RunWorkList>d__20.MoveNext () [0x00000] in <filename unknown>:0 

10:00:03 PM - Done. Elapsed running time: 1.0752851 seconds
```

Fresh install, no mods

**Comment by BertMechman** [comment]
I can see that their has been a modification to the MetadataDatabase.cs.  I cannot figure out how to build the project with Blend for Visual Studio to produce new modtek packages/

**Comment by razor85416** [comment]
Same for me as well.
I know i'm kinda late but have they been able to fix it yet?.

**Comment by Mpstark** [comment]
0.7.1 should resolve the compatibility issues with 1.5 BattleTech
