### ISSUE TITLE
Modtek 7.1, Battletech 1.5

### ISSUE THREAD

**Issue by RDZ1122** [BattletechModders/ModTek#136]
Does load/launch unlike 7.0, but once in-game, cannot access Contracts.  Just spinning icon indefinitely, without contracts populating.  Everything else seems to work so far.

**Comment by Fareolla** [comment]
I have the same problem.

**Comment by PauloMBrito** [comment]
In new game i have the contract problem.
With old games i get the can't load problem

**Comment by chrisleson** [comment]
In my case it's been the IRBT14MadlibsFix mod. It should no longer be used with BT 1.5
