### ISSUE TITLE
ModTek 7.2, Battletech 1.6.1-542R 2 DLCs

### ISSUE THREAD

**Issue by JohnDoeMOO** [BattletechModders/ModTek#143]
Unfortunately, I am not a programmer, so I will not be able to help in this case. However, I am able to describe the problem. 
After injection (ModTek 7.2, no mods added) the game starts as normal. But as soon as you start a career, after choosing the character and starting a new game, the game freezes. You have to manually close the game via Task Manager. After a roll-back, the game works fine again. So this issue is related to this ModTek version.

**Comment by Mpstark** [comment]
This is the first time that I've heard of this, mind posting `output_log.txt` out of the `BATTLETECH/BattleTech_data/` folder during a lockup like this? Generally the problem is easier to diagnose from there.

**Comment by JohnDoeMOO** [comment]
You are right. According to outout.log, it is a D3D/DX11 error. Issue can be closed.
