### ISSUE TITLE
Infinite loading for saved games

### ISSUE THREAD

**Issue by MattyBlack** [BattletechModders/ModTek#144]
After the patch I re-injected modtek and then everything went haywire. I've done a complete reinstall of both modtek and Community asset bundle, as well as BT 3025. The game loads fine but when I get to the campaign/career/skirmish I get the infinite loading circle. I've reinstalled my save games I've also deleted them so I have no games saved. but I still get the infinite wheel.

Any ideas on what can cause this? Is there a fix?
Any help would be appreciated as I love this game, and love using my saves.

Cheers

**Comment by Mpstark** [comment]
If you're using BetterAI (I think this may be included with BEX3025), you may want to update that to the latest hotfix. If that doesn't work, upload `BATTLETECH/BattleTech_data/output_log.txt`

**Comment by MattyBlack** [comment]
Thanks for that Mpstark, so where can I find this hot fix? did do a google search but not sure what's the correct one to use.

Cheers

**Comment by Mpstark** [comment]
https://github.com/BattletechModders/BetterAI/releases
