### ISSUE TITLE
Bug: ModTek strips white spaces from mods name and description fields

### ISSUE THREAD

**Issue by leviathan13** [BattletechModders/ModTek#146]
I'm not sure how or when, although it's probably when enabling/disabling mods, but sometimes ModTek strips all white spaces from the name and the description of the mods manifests.

**Comment by Mpstark** [comment]
ModTek should never write to mod.json files, what circumstances are you referring to?

**Comment by leviathan13** [comment]
Every time I enable/disable mods from ModTek, it writes the mod.json files (to change the "Enabled" flag). Should I not use the manager anymore to enable or disable mods? Removing white spaces is the only inconvenience I noticed so far though (it also changes some indentation, so it's probably some kind of syntax/code parsing thing).

**Comment by Mpstark** [comment]
ModTek does not contain an external manager program, nor is affiliated with any. I'm unsure what you're using -- I do remember hearing about a program that was being developed, but that was a while back and I don't remember hearing that it had a release.

**Comment by leviathan13** [comment]
Oh, I'm sorry, I think I assumed that the [BML](https://www.nexusmods.com/battletech/mods/263) was part of ModTek... I'll report it to them then.
