### ISSUE TITLE
Suggestions: generate cache and change load order from manager

### ISSUE THREAD

**Issue by leviathan13** [BattletechModders/ModTek#147]
I'd like to make two suggestions:

- **Add a "generate cache" button**. This will generate/update ModTek cache with all currently enabled mods, basically doing the same thing it does when launching the game but without launching the game itself. I would find this helpful for checking errors, creating and testing new mods because you can often see if there are issues with a single mod or compatibility issues with multiple mods by checking the generated cache.
- **Change load order from ModTek window.** I know that you can change the load order by the file in the modtek folder, but I think it would be more intuitive and easier if you could do that from the ModTek manager window. IIRC if you enable/disable new mods, the load order file will be rewritten, so you also need to start the game twice in order to set up the proper load order (once to generate the file and then another one after you edited it).

Apologies if you can already do that, in that case I'd like to know how, thanks.

Using ModTek 0.7.2.

**Comment by Mpstark** [comment]
ModTek is very specifically written as a assembly that is run at the start of the game launch. While this could be decoupled, I don't believe that the benefit is worth the time investment to do. We're also not looking to add additional management options to ModTek at this time.

TBH, we're is in a little bit of a feature freeze as we wait for news of what HBS is going to be adding in future patches.

**Comment by leviathan13** [comment]
I don't know how it works, so I thought adding the "generate cache" button was a quick thing to do since it does it already every time, but if indeed it's much work, then ok. It was just a QoL suggestion, not functional.
