### ISSUE TITLE
Better instructions for macOS

### ISSUE THREAD

**Issue by ksignorini** [BattletechModders/ModTek#150]
Please change your "ModTek 0.60.0 and after" instructions to include macOS install. You do a nice job for pre-0.60.0. Here's my suggestion for a separate macOS instruction set:

> macOS Instructions
> 
> 1. On macOS use the following directory instead of the BATTLETECH directory: ~/Library/Application\ Support/Steam/steamapps/common/BATTLETECH/BattleTech.app/Contents/Resources/
> 2. If the Mods directory doesn't exist, create it here: ~/Library/Application\ Support/Steam/steamapps/common/BATTLETECH/BattleTech.app/Contents/Resources/Mods/
> 3. Move the entire ModTek folder from the release download into the /Mods/ folder created above.
> 4. You should now have a ~/Library/Application\ Support/Steam/steamapps/common/BATTLETECH/BattleTech.app/Contents/Resources/ModTek/ folder
> 5. Run the injector program (ModTekInjector.exe) in that folder. To do this:
> 	a. Open a Terminal window.
> 	b. At the command line, type "cd ~/Library/Application\ Support/Steam/steamapps/common/BATTLETECH/BattleTech.app/Contents/Resources/Mods/" and press Return.
> 	c. At the command line, type "mono ModTekInjector.exe" then press Return to run the injector.
> 6. DO NOT move anything from the /Mods/ModTek/ folder, it is self-contained.
>

**Comment by Mpstark** [comment]
I've updated the macOS directions, thank you, sorry for taking nearly a month to do so. I really do appreciate this kind of thing, but I've been swamped at a new job.
