### ISSUE TITLE
BTModLoader.log contains error only message on linux

### ISSUE THREAD

**Issue by BlueWinds** [BattletechModders/ModTek#154]
ModTek works great, I've been playing with BTA 3062 for a while now. However, BTAModLoader.log contains only an error message claiming that it couldn't find itself.

[BTModLoader.log](https://github.com/BattletechModders/ModTek/files/3639975/BTModLoader.log)

![image](https://user-images.githubusercontent.com/3003404/65391472-6aad2400-dd1e-11e9-86e8-af51451634e6.png)

The path in the error message is the path to the file itself, so I'm not sure what it's complaining about, but I assume there's supposed to be something else in here? I discovered the issue because I'm trying to debug a different mod, and assumed this file would have something helpful in it.

**Comment by Mpstark** [comment]
You'll want to run `cat` instead of `ls` to get the contents of the file. The only thing that I know causes this is AIM, which is outdated and broken in 1.6+. CAC might also do it, since it ate a lot of AIM, but I'm not sure for certain.

**Comment by BlueWinds** [comment]
I attached the log file itself in addition to the image in the initial report, `ls` was just to point out the fact that the path exists. CAC/mod.json says version 0.1.58, the one included with BTA's 3.0.0 release, but I'm not sure that's related - the error looks like it comes from `Sheepy.BattleTechMod.BattleMod.GetModList ()`, which looks to my eyes more like a ModTek thing than an error with CAC.

Anyway, here's the log file again, just in case: [BTModLoader.log](https://github.com/BattletechModders/ModTek/files/3640171/BTModLoader.log)

**Comment by Mpstark** [comment]
Yes, this error is due to Sheepy (who made AIM) doing some funky stuff with BTModLoader.log to see what mods were loaded. AIM was ingratiated into CAC and I guess that the CAC authors didn't bother fixing this.

The log file is harmless by itself, and it doesn't seem to affect AIM/CAC functionality.

**Comment by BlueWinds** [comment]
Ok, I'll take it up there, thank you for your help! :+1:
