### ISSUE TITLE
v0.7.3 does not work with BT < 1.7

### ISSUE THREAD

**Issue by helge000** [BattletechModders/ModTek#155]
Current release of ModTek (v0.7.3) is not loading if you run game version 1.6 in my case. Downgrading to 0.7.2 solves the issue.

**Comment by Mpstark** [comment]
This is expected behavior, the full name of the release is:

> v0.7.3 for BattleTech 1.7

It's made even worse by changes to the .NET/mono versions. Downgrading to the last release that supported 1.6 is the path forward as you've pointed out.
