### ISSUE TITLE
AdvancedJSONMerge for difficultyList?

### ISSUE THREAD

**Issue by DerKastellan** [BattletechModders/ModTek#156]
Hi!

I tried to create an AdvancedJSONMerge for the "difficultyList" or more particularly the "diff_BS_high" (and similar keys) as TargetIDs. Unlike other similar merges it never seems to resolve.

I noticed that the "difficultyList" exists exactly twice for career and campaign and neither of them has a unique key, so I guess the problem is looking these up or distinguishing them?

I found that the existing mod (BT 3062 Advanced) I compared for reference seems to simply replace the whole file instead of merging into specific fields. Maybe other people had this problem, too?

I read your code for a while but it seems to be a straight lookup and ID is the only key.

Is there any additional information I can supply in either mod.json or in the .json containing the merge to make it access the relevant IDs? I wouldn't mind changing both (career & campaign) at the same time. 

Thank you.

**Comment by Wulfbanes** [comment]
Hey DerKastellan, if you're still looking into this, I am pretty sure I have done exactly this for BTA. Check out the BT Advanced Starters folder in the main release.
