### ISSUE TITLE
README.md documentation incorrect

### ISSUE THREAD

**Issue by Eck** [BattletechModders/ModTek#158]
Currently the only dataAddendum that is wired up on HBS's end is the FactionEnumeration. The documentation implies that it works for every dynamic enum, but that isn't correct. I'm hoping to implement the rest of them after we get the higher priority ModSupport issues solved. Could be in 1.8.x or maybe 1.9 by the time I get it fixed.

- HBS_Eck

**Comment by CMiSSioN** [comment]
i've implemented support on my side - and checked they working 
https://github.com/BattletechModders/ModTek/blob/acc09e77e2a841a2355d5f8f0ba8c6604916db5c/ModTek/ModTek.cs#L1397
