### ISSUE TITLE
Exception after downgrading to BT1.7 w/ ModTek 0.7.3

### ISSUE THREAD

**Issue by chrkuhlmann** [BattletechModders/ModTek#159]
Hi,

I'm trying to go back to 1.7.1-598R since many of my beloved mods are not (yet) available for 1.8 (e.g. AIM).

Unfortunately Steam did an auto update and I'm trying to roll back the changes (via [this method](https://steamcommunity.com/sharedfiles/filedetails/?id=1086279994)). 
It worked pretty well for the basic game, but as soon as I try to run ModTek I cannot start a new campaign any more (shows loading indicator, and never stops). Loaded saves are also stuck and never stop loading, though the UI is shown and I can e.g. open mechbay. 
This happens whether or not I have any mods installed. As soon as ModTek (0.7.3) is loaded it crashes: 
``` 
NullReferenceException: Object reference not set to an instance of an object
  at ModTek.Patches.GameTipList_ctor_Patch.Postfix (System.String filename, System.Collections.Generic.List`1[T] ___tips) [0x00037] in <2affd5aa398542ff9bc7dda52df0924f>:0 
  at (wrapper dynamic-method) BattleTech.GameTipList..ctor_Patch1(object,string,int) 
```
[output_log.txt](https://github.com/BattletechModders/ModTek/files/3926244/output_log.txt)
[harmony_summary.log](https://github.com/BattletechModders/ModTek/files/3926247/harmony_summary.log)
[ModTek.log](https://github.com/BattletechModders/ModTek/files/3926250/ModTek.log)

I tried to delete settings files and registry keys but none worked. Any Ideas how to fix this? Any help is highly appreciated.

**Comment by LadyAlekto** [comment]
You know you can just opt into 1.7.1 in steam under betas to rollback your version?

Like thats the most complicated way to get a older version of the game

**Comment by chrkuhlmann** [comment]
Ok, will try that,. Thank you very much for the suggestion. 
For reference, the exception I've seen comes from 
```
public static class GameTipList_ctor_Patch
	{
		public static void Postfix(string filename, List<string> ___tips)
```
where ___tips is null but not checked before being accessed.
However, solving this creates another null exception at an internal game file, so I will try to use your method to roll back and report back what happens. Hopefully this is just a broken install.

**Comment by CMiSSioN** [comment]
this way is not only complicated - it is not working - all your problems are certainly caused by wrong game's main DLL version.

**Comment by chrkuhlmann** [comment]
Ok, used the beta method and game seems to be working again. Thanks a lot guys, didn't know about this method. Well, at least I gained a little insight into modtek through this. Thanks again.
