### ISSUE TITLE
Please update install instructions

### ISSUE THREAD

**Issue by amezick** [BattletechModders/ModTek#175]
I downloaded ModTek-0.7.7.4.zip from the "releases" page.  This archive contains the directory "ModTek-0.7.7.4".  So in D:\SteamLibrary\steamapps\common\BATTLETECH\Mods I had the directory "ModTek-0.7.7.4".  The injector worked fine.  The game would not load ModTek on startup.  Once I changed the directory to just "ModTek" the game would load ModTek as expected.  Please either 1) include a note about the importance of the directory name in your wiki, or 2) change your app to allow different directory names for your files.

Thank you for all you have done for the Battletech community.  I very much appreciate all of your hard work!

**Comment by Mirco1502** [comment]
You're my hero Sir.

I was really desperated not able to make the mods work.

This should really getting changed or mentioned like you suggested.
