### ISSUE TITLE
documentation install linux steam ModTek 0.6.0 and after

### ISSUE THREAD

**Issue by f-abel** [BattletechModders/ModTek#176]
This works for ubuntu 18.04.4 LTS (Bionic Beaver) with Battletech  1.9.1 
in `$HOME/.steam/steam/steamapps/common/BATTLETECH `
(for newbies $HOME stands for ~, the /home/username directory ) 
create if doesn't exist Mods directory
then `cd $HOME/.steam/steam/steamapps/common/BATTLETECH/Mods` and unzip the ModTek-{xyz}.zip there.
Rename the directory created (likely ModTek-{xyz}) to ModTek.
install mono package (I installed all mono packages, surely less required)
then from within ` $HOME/.steam/steam/steamapps/common/BATTLETECH/Mods/ModTek/` directory,
in command line run
```
mono ModTekInjector.exe
```
it should work like a charm.
check injected : 
from within `$HOME/.steam/steam/steamapps/common/BATTLETECH/Mods/ModTek/` directory,
in command line run
```
mono ModTekInjector.exe /d
ModTek Injector
---------------

ModTek Injected
```

Then you are done .

If you had mods with the legacy HBS in `$HOME/My Games/BattleTech/mods`
They won't load anymore.
Move the `$HOME/My Games/BattleTech/mods` directory content (except the HBS directory and load_order.json,  modloader.log,  modloader_previous.log files) to the directory `$HOME/.steam/steam/steamapps/common/BATTLETECH/Mods`
Then you are migrated .

For troubleshoot purpose : 
modloader logs moved from  `$HOME/.steam/steam/steamapps/common/BATTLETECH/DumpBox/*`
to `$HOME/.steam/steam/steamapps/common/BATTLETECH/Mods/.modtek` (beware the dot !)

**Comment by f-abel** [comment]
fixed a typo thank you catlady

**Comment by JLB39401** [comment]
I tried this and had some (as yet still unresolved) trouble. I opened the Terminal in the ModTek directory (the highest level one, just under Mods, that I had recently renamed from ModTek-0.7.7.6) and typed in the mono command.  It looked like this:

/usr/data/SteamLibrary/steamapps/common/BATTLETECH/Mods/ModTek$ mono ModTekInjector.exe
Cannot open assembly 'ModTekInjector.exe': No such file or directory. 

A quick search showed no ModTekInjector.exe file anywhere; do I need to compile one?  How would I do that?  Thanks for any assistance.

**Comment by f-abel** [comment]
Did you unzip the ModTek.zip file ? don't you have a subdirectory in it to up level ?
I just checked https://github.com/BattletechModders/ModTek/releases/download/v0.7.7.6/ModTek.zip the ModTekInjector.exe file is in it. I noticed in the zip file, the directory is now named ModTek.
Remember the ModTekInjector.exe file need to be located in the Mods/ModTek directory.

**Comment by JLB39401** [comment]
I got the .tar file, and extracted that.  After extraction I have a ModTek-0.7.76 directory (which I renamed to just ModTek, and placed in the Mods directory) which contains six other directories: ModTek; ModTekAutoInjector; ModTekInjector; ModTekInstaller; ModTekUnitTests; and ModTekZipCreate.  There are also nine files on that level, none is an .exe file.

**Comment by f-abel** [comment]
You downloaded the source : the release got the binary.
On right end column on [main page](https://github.com/BattletechModders/ModTek) you got the about then the release.
or you can use [this direct link](https://github.com/BattletechModders/ModTek/releases) to get to the releases (compiled code)

**Comment by JLB39401** [comment]
.... and, just like that, it seems to be working.  Sorry for the boneheaded mistake; and thank you for your help!
