### ISSUE TITLE
how do I get rid of the damn thing

### ISSUE THREAD

**Issue by exekutive** [BattletechModders/ModTek#179]
After I installed ModTek, no mods would work. So I want to start again.

How do I remove it?? There are no instructions anywhere.

**Comment by janxious** [comment]
https://github.com/BattletechModders/ModTek/wiki/The-Drop-Dead-Simple-Guide-to-Installing-BTML-&-ModTek-&-ModTek-mods#uninstalling is *probably* still correct

**Comment by exekutive** [comment]
I eventually figured it out my own. There are TWO mods folders. I wish this had been explained at the beginning...

The default Hare Brain Studios mods folder in 'My Documents'. This is where you put mods if you're NOT using ModTek.

When you install ModTek, it goes in the Program Files/Battletech/Mods folder. When you install mods that DO use ModTek, they go here. If you put them in the Documents one when ModTek is installed, they won't work.

To remove ModTek, remove the ModTek and .modtek folders from Program Mods. If something else is being 'injected' then I don't know how to remove that. Maybe it's in the other mod folder.

The drop dead simple guide definitely wasn't for me and I'm not completely retarded. Figuring out which files to download was confusing too.
