### ISSUE TITLE
More Sophesticated Load Order Handling

### ISSUE THREAD

**Issue by Mpstark** [BattletechModders/ModTek#18]
Currently load order is done in rounds and the first mod to be loaded "wins" any conflicts. Also, there is not yet a way to specify load order.

A better solution would maximize number of loaded mods while also following any specific directives in a some sort of specified load order file.

**Comment by CptMoore** [comment]
>  I hope its sorted by mod name.

Just saw that it isn't so I'll make sure the load order is deterministic, you'll see a PR soon about this.

**Comment by Mpstark** [comment]
ModTek now handles loading load order from a file in 0.2.0
