### ISSUE TITLE
[Performance] - AddToDBLoop Exists check

### ISSUE THREAD

**Issue by m22spencer** [BattletechModders/ModTek#180]
https://github.com/BattletechModders/ModTek/blob/master/ModTek/ModTek.cs#L1434

This Exists check is rather expensive. Possibly convert BTRLEntries to a Dictionary, or keep a HashSet with the file name to speedup this check.

~2-5s of roguetech modtek init.

Just putting this here for tracking purposes.

**Comment by CptMoore** [comment]
after the refactoring in #191 there will be new performance issues
