### ISSUE TITLE
AddToDBLoop accessing outdated BTRLEntriesPathes

### ISSUE THREAD

**Issue by mcb5637** [BattletechModders/ModTek#189]
AddToDBLoop checks if a file is still valid with the HashSet BTRLEntriesPathes https://github.com/BattletechModders/ModTek/blob/a59bc5b724144cf6046f03880e30dcfc944188fc/ModTek/ModTek.cs#L1482.
That HashSet is Created at the end of HandleModManifestsLoop https://github.com/BattletechModders/ModTek/blob/a59bc5b724144cf6046f03880e30dcfc944188fc/ModTek/ModTek.cs#L1395,
but AddBTRLEntries gets changed in MergeFilesLoop, which gets executed between these 2 functions.

The result is that every file, that got any merges, gets removed from the Database and then added again, with exactly the same path.
The log looks like this;
```
Loaded db cache.
	Need to remove DB entry from file in path: Mods/.modtek/Cache/BattleTech_Data/StreamingAssets/data/contracts/assassinate/Assassinate_HardTarget.json
	Need to remove DB entry from file in path: Mods/.modtek/Cache/BattleTech_Data/StreamingAssets/data/contracts/capturebase/CaptureBase_AbandonedFactory.json
	Need to remove DB entry from file in path: Mods/.modtek/Cache/BattleTech_Data/StreamingAssets/data/contracts/capturebase/CaptureBase_BargainingChip.json

(...)

		Replaced DB entry with an existing entry in path: Mods/.modtek/Cache/BattleTech_Data/StreamingAssets/data/contracts/assassinate/Assassinate_HardTarget.json
		Replaced DB entry with an existing entry in path: Mods/.modtek/Cache/BattleTech_Data/StreamingAssets/data/contracts/capturebase/CaptureBase_AbandonedFactory.json
		Replaced DB entry with an existing entry in path: Mods/.modtek/Cache/BattleTech_Data/StreamingAssets/data/contracts/capturebase/CaptureBase_BargainingChip.json

(...)
```

The easiest fix is to recreate the BTRLEntriesPathes HashSet after MergeFilesLoop finishes execution.

**Comment by CptMoore** [comment]
The whole BTRL loading process is being redone in #191 .
