### ISSUE TITLE
Infinite loading screen

### ISSUE THREAD

**Issue by Bansheedragon** [BattletechModders/ModTek#194]
I'm hoping I can get some help here as it seems I can't get any help anywhere else.
I wanted to use some mods for my game, but unfortunately as soon as I just activate modtek alone I end up with an endless loading screen when trying to start a new game.

I tried every troubleshooting solution I can find, including a fresh install of the game with only modtek, but nothing seems to work.

Looking at the modtek.log file I get the impression something is failing or conflicting, but I have no idea if I'm even reading it correctly, much less how to fix it.

[ModTek.log](https://github.com/BattletechModders/ModTek/files/6603997/ModTek.log)

**Comment by CptMoore** [comment]
@Bansheedragon can you try the latest pre-release again?

**Comment by CptMoore** [comment]
can you provide the .modtek/battletech_log.txt log?

**Comment by Bansheedragon** [comment]
As requested, battletech_log.txt

[battletech_log.txt](https://github.com/BattletechModders/ModTek/files/6618224/battletech_log.txt)

**Comment by CptMoore** [comment]
ok looks actually alright, try with the latest again (dont think it'll help), you might need to remove some of mods again like you tried before

**Comment by Bansheedragon** [comment]
Removed all mods and installed only modtek.
Still can't get it to work.

[battletech_log.txt](https://github.com/BattletechModders/ModTek/files/6618546/battletech_log.txt)
[ModTek.log](https://github.com/BattletechModders/ModTek/files/6618549/ModTek.log)

Hopefully this can provide some insight for you

**Comment by CptMoore** [comment]
does the old modtek v0.8.0 work?
does the old modtek v0.7.7 work if you use it again?

unfortunately I dont get anything out of those logs that stands out differently to what I have, except that you don't own the shadowhawkdlc, if i disable that on my end everything still loads up though.

you also use windows and steam.
log entries are as they supposed to be (no modded content => nothing to re-build).

**Comment by Bansheedragon** [comment]
I use the 0.7.7.7 and it works just fine, I have not tried 0.8.0.
After trying out the latest build(2.0.2) I went back to 0.7.7.7 again and everything was working fine again.

The shadow hawk dlc is only an alternate skin for the shadow hawk mech, so I don't see how that would have any affect.
I don't know what else could be the reason it does not work unless its something with either steam or windows itself.

**Comment by CptMoore** [comment]
ok, I'm trying to find a way to reproduce it so, I think it happens to me too now, what do you mean by "infinite loading screen"?
- never get the main menu?
- loading into a campaign/carreer stays under infinite loading?
- loading into the skirmish mechbay/mechlab stays under infinite loading?

**Comment by Bansheedragon** [comment]
When I try to load an existing or start a new campaign, not tried the other options as I'm more interested in the story, I get the loading wheel in the top left.
It just stays there spinning from the beginning and just never goes beyond that, unlike when it works as intended and the loading wheel actually pauses occasionally because its loading.

**Comment by CptMoore** [comment]
please try again with the newest latest

**Comment by Bansheedragon** [comment]
I got good news this time.
I was able to start a new game, both with modtek alone and mods installed.
I was also able to load an existing game and play a mission without any problems.

No battletech_log.txt file seems to have been created this time, but I can provide the modtek.log file in case there is some information there you want

[ModTek.log](https://github.com/BattletechModders/ModTek/files/6623314/ModTek.log)

**Comment by CptMoore** [comment]
not good news, you ran it with the old 0.7.7 😄 
> ModTek v0.7.7 -- 2021-06-08 7:13:55 PM

see https://github.com/BattletechModders/ModTek/releases/tag/latest for the latest
when you right click on the ModTek.dll you should see the version under "Product version"

Example, this is version 2.0.2+9 (+9 means there are 9 changes since version 2.0.2)
![image](https://user-images.githubusercontent.com/39010654/121350807-63331180-c92b-11eb-81ea-16421977cb70.png)

**Comment by Bansheedragon** [comment]
I was certain I had the right version installed.
My brain must have taken a left turn when it should have taken a right.

In any case I tested again, and this time made triple sure by checking each time I tried that I had the right version.
My statement from above still holds true, I was able to run things with no problems

And this time I got all the logs as well

[battletech_log.txt](https://github.com/BattletechModders/ModTek/files/6623887/battletech_log.txt)
[ModTek_runtime_log.txt](https://github.com/BattletechModders/ModTek/files/6623888/ModTek_runtime_log.txt)

**Comment by CptMoore** [comment]
excellent! thanks for testing and hanging on! really helped me to find that career/campaign starting/loading issue

also will improve the version display in ModTek a bit

the log files look as expected
