### ISSUE TITLE
JumpJetDef Handling Error Causes NullReferenceExceptions

### ISSUE THREAD

**Issue by korgano** [BattletechModders/ModTek#203]
ModTek version 2.0.6

ModTek will find JumpJetDef JSON files in folder declared in mod.json, and add said JSONs to Manifest.CSV, but **not** to the game's list of items. This then causes crashes whenever said JSONs are called on, such as during the Bonus Rewards process or when starting combat with a unit equipped with said jumpjets added via console.

I have video of the bug happening in real-time in DNSpy: 
[![BattleTech 1.9.1 w/ ModTek 2.0.6 JumpJet error](http://img.youtube.com/vi/LbBAHm5nuQw/0.jpg)](https://www.youtube.com/watch?v=LbBAHm5nuQw)

I also have screencaps of the ModTek log and Manifest, which show that ModTek at least partially completed the task of adding the jumpjets to the game:
![ModTek log showing multiple custom jumpjets added to the game](https://user-images.githubusercontent.com/1180905/188025900-ac72c411-d1c5-4dc2-a4bf-31b75ce27f3c.png)
![Modded Manifest.CSV showing custom jumpjets with proper filepaths](https://user-images.githubusercontent.com/1180905/188026268-5119622f-7085-4728-b3a5-7add0a37ead9.png)

Process to reproduce:
-Create a folder for jumpjet templates and at least one jumpjet template
-Associate folder with JumpJetDefs in mod.json file
-Create itemCollection file/reward event that gives player custom jumpjet
-Load into save right before Reward UI appears
-Use DNSpy to find ShopDefItem.ToSalvageDef
-Setup breakpoints throughout ShopItemType.JumpJet
-Custom jumpjet will pass 'jumpJetDef = null'
-At 'if (jumpJetDef != null)', process will skip back to beginning upon null JumpJetDef reading
-NullReferenceException error occurs after game runs through reward process

**Comment by wmtorode** [comment]
Created a custom jumpjetdef and was able to load it into the game without issue. 

Custom jumpjet showed up in skirmish mechbay and on a custom mechdefs created to test it and was able to be deployed without issue.

Was further able to load into the skirmish mechbay with an example jumpjet def provided by the reporter without issue.

Finally the above data shows modtek to be acting correctly as it does indeed find the jump jet and add it to the manifest with the correct file path, that the datamanager fails to load the def is not a modtek issue.

**Comment by wmtorode** [comment]
[JwTest.zip](https://github.com/BattletechModders/ModTek/files/9483379/JwTest.zip)
Test mod used to prove out correct loading of custom jumpjetdefs
