### ISSUE TITLE
Modteck is breaking story Timelines

### ISSUE THREAD

**Issue by xeryx01** [BattletechModders/ModTek#205]
There is a conflict that did not exist in prior Modteks that is breaking story timelines. As I can run XAI just fine in version 0.8.0 for sure and I think the early 2.1 worked fine as well. But now since all previous versions have been removed from your Git, many new players have been uploading your newest file and telling me that the timeline is breaking in story mode only. I am not a coder so I do not know the intricacies of your code and we could use your help in solving this problem. It is incompatible and corrupting the savegames, with Pilot Quirks

**Comment by CptMoore** [comment]
@xeryx01 sorry for the troubles, originally I wanted to remove non-used releases and only keep 0.8 and 2.6 but more got removed.
I tried restoring 0.8 and 2.6 so you can still use them.
I've re-written the descriptions to make that clear for the users.

**Comment by CptMoore** [comment]
I have some time to look at it later, ill see if there are issues i can help with

**Comment by CptMoore** [comment]
Ok, the big thing that ModTek changes in 2.1/3.0 is that the location of the main assembly is different. Maybe Pilot Quirks or some mod that it depends on, uses the Assembly.Location, and that leads to corruption as its now different. Otherwise I would not know what could cause it. If that is the cause however, ModTek can't fix it from its side, the mods need to be patched.

**Comment by xeryx01** [comment]
Yeah, this is possible the issue Pilot quirks maybe cause trouble trying to isolate it down. I was a bit frustrated at the time since I am not a coder, and it is really difficult to understand what is going on sometimes. I will keep looking into it this weekend.  It is really a strange problem I am having. Save games are the issue I am having. once a save is loaded it breaks the timeline. Thanks for your hard work, I know it can't be easy!

**Comment by xeryx01** [comment]
I found the issue in the Milestones and a collapsed array, so I am closing the ticket thanks for the help.
