### ISSUE TITLE
Some error

### ISSUE THREAD

**Issue by eqholic** [BattletechModders/ModTek#206]
After installing ModTek I get this error message:
<img width="1280" alt="Harmony_Error" src="https://user-images.githubusercontent.com/30209172/191858628-a5a05e40-6a6e-4dc5-b82e-6b1575712e0e.png">

**Comment by CptMoore** [comment]
Oh you must have used the latest (unstable) test with harmonyX a short while ago. just use the newer latest version from https://github.com/BattletechModders/ModTek/releases

**Comment by CptMoore** [comment]
If you still have the error with the latest version please reopen.

**Comment by eqholic** [comment]
Unfortunately the error persists with 3.0.0.
<img width="1280" alt="Harmony_Error_02" src="https://user-images.githubusercontent.com/30209172/192161761-df3c5868-ada2-4c9e-acf1-79024e89a780.png">

**Comment by CptMoore** [comment]
Can you attach a zip with the files found in /Mods/.modtek ?

**Comment by CptMoore** [comment]
Should be fixed with with 3.0.1

**Comment by eqholic** [comment]
Works indeed. Thanks.
