### ISSUE TITLE
Mission objective erroring out

### ISSUE THREAD

**Issue by xeryx01** [BattletechModders/ModTek#207]
![ErrorMissionV3](https://user-images.githubusercontent.com/45599120/192150124-6b1995bf-9be6-4c68-80f1-0ee308927988.PNG)
V3.0 
Gave it a spin and am having additional mission objectives fail for some reason.  I didn't have this issue with 2.0.6 I think it was.
[.modtek3_XAI.zip](https://github.com/BattletechModders/ModTek/files/9641004/default.modtek3_XAI.zip)

**Comment by CptMoore** [comment]
Can you right mouse click on BATTLETECH/Mods/ModTek/AssembliesOverride/0Harmony.dll and tell me what version it is under details?
Then you can delete the folder BATTLETECH/Mods/ModTek/Harmony12X and try again

**Comment by CptMoore** [comment]
Nevermind, might be a different issue. I think i found a suspicious exception in your attached logs
