### ISSUE TITLE
Linux + Steam + 3.0.1

### ISSUE THREAD

**Issue by RX-O** [BattletechModders/ModTek#208]
The run.sh fails to connect with the Steam shell and aborts.

I'm running EndeavorOS with Gnome
I'm fairly new to this, so please let me know what kind of reports you need.

2.0.6 works like a charm

**Comment by CptMoore** [comment]
Can you follow the guide at https://docs.bepinex.dev/master/articles/advanced/steam_interop.html ?
Make sure to use "run.sh" instead of "run_bepinex.sh" and ignore any instructions about bepinex!
If that works I'll adjust the readme for ModTek.

**Comment by RX-O** [comment]
Now it works.

Thanks a lot.
