### ISSUE TITLE
Doesn't seem to work with GOG's version on Linux

### ISSUE THREAD

**Issue by Dwosky** [BattletechModders/ModTek#210]
I'm using GOG Battletech's version 1.9.1 and I don't seem to be able to make it work with ModTek.

I've unzipped the release (stable) file to `$HOME/GOG Games/BATTLETECH/game`, which is where the `Battletech` executable and its data resides. I've tried both launching `run.sh` script directly from there as well as updating the `start.sh` (GOG's script) to point to `run.sh` instead of the executable, but Battletech's executable seems to crash in the middle.

Running with the `run.sh` I get the following output and then it brings me back the prompt:
```
Set current directory to /home/peter/GOG Games/BATTLETECH/game
Found path: /home/peter/GOG Games/BATTLETECH/game/BattleTech
Mono path[0] = '/home/peter/GOG Games/BATTLETECH/game/BattleTech_Data/Managed'
Mono config path = '/home/peter/GOG Games/BATTLETECH/game/BattleTech_Data/MonoBleedingEdge/etc'
```
If I run `Battletech` executable directly (or with the unmodified GOG `start.sh` script), I get the following
```
Set current directory to /home/peter/GOG Games/BATTLETECH/game
Found path: /home/peter/GOG Games/BATTLETECH/game/BattleTech
Mono path[0] = '/home/peter/GOG Games/BATTLETECH/game/BattleTech_Data/Managed'
Mono config path = '/home/peter/GOG Games/BATTLETECH/game/BattleTech_Data/MonoBleedingEdge/etc'
Preloaded 'ScreenSelector.so'
Preloaded 'libAkFlanger.so'
Preloaded 'libAkGuitarDistortion.so'
Preloaded 'libAkSoundEngine.so'
Preloaded 'libAkStereoDelay.so'
Preloaded 'libAkTremolo.so'
Preloaded 'libBink2x64.so'
Preloaded 'libBinkPluginLnx64.so'
Preloaded 'libSDL2-2.0.so.0'
Preloaded 'libasound.so.2'
Preloaded 'libc.so.6'
Preloaded 'libopenal.so.1'
Preloaded 'libsndio.so.6.1'
Display 0 [...] (primary device).
Logging to /home/peter/.config/unity3d/Harebrained Schemes/BATTLETECH/Player.log
```

So I was wondering if GOG's version its supported or if I need to perform any other additional task in order to have it working.

**Comment by Dwosky** [comment]
Sorry, nevermind, seems that launching the game from the desktop shortcut seems to load ModTek without issues. In case anyone needs a little more input on how to configure GOG's version, I just edited the `start.sh` file that comes with the instalation itself and changed the executable line to `run.sh`, which is the script that comes from ModTek:
```
# Actions
    run_game() {

      echo "Running ${GAME_NAME}"
      export LC_ALL=C
      cd "${CURRENT_DIR}/game"    
      ./run.sh
      #chmod +x "BattleTech"
      #./"BattleTech"		 	

    }
```

**Comment by CptMoore** [comment]
I've added a minimal version of your instructions to the README.
