### ISSUE TITLE
Release tagged as 2.0.6 has 2.0.7 named binary

### ISSUE THREAD

**Issue by scotsman42** [BattletechModders/ModTek#213]
This is probably a very minor thing but the release tagged 2.0.6 https://github.com/BattletechModders/ModTek/releases/tag/v2.0.6 has "ModTek_2.0.7.zip" as the listed zip.

**Comment by CptMoore** [comment]
fixed as https://github.com/BattletechModders/ModTek/releases/tag/v2.0.7
