### ISSUE TITLE
Modtek is missing an injector.exe

### ISSUE THREAD

**Issue by Daniel14541** [BattletechModders/ModTek#215]
As the title explains it. I downloaded modtek in the appropriate file so that mods was under battletech. I copied over the mods I wanted to run from vortex into the mods file. I went into the modtek folder and the only injector listed is a folder so I go into that and find that the only file found in there is a ModTekInjector.ddl

I double click it to run it and up pops a folder saying I am trying to open a system file rather then an executable. I'm assuming that the old instructions to run injector no longer apply but when I go into the game and select the mods to run and start a new campaign up it just loads forever. So am I missing the injector? That is what I think the problem is but I'm unsure.

Everspinny is detected and supposedly the process has been dumped to log but I have no idea where I might find that log.

**Comment by CptMoore** [comment]
Vortex is not supported sorry.

The .dll is not supposed to be run by you, it will be run by the ModTekPreloader.dll which also is not run by you!
You actually just have to start BattleTech.exe .
That will trigger winhttp.dll ( which is actually UnityDoorstop ).
Then ModTekPreloader.dll will be called.
Then ModTekInjector.dll will be called.
Then ModTek.dll will be called.

**Comment by Gogopex** [comment]
This makes it much harder to run ModTek on OSX/Linux w/ mono -- any workarounds @CptMoore? Launching the game through OSX does not seem to trigger that chain.

**Comment by CptMoore** [comment]
Its using unitydoorstop and that was developed by a guy/people who also help with bepinex, a generic modding framework for unity. So for issues one can also research there. Most recent and current knowledge is always found in the bepinex discord and wiki.

MacOS, Linux, Windows
Steam/GoG
Wine/native

Are all supported combinations by unitydoorstop, but some require extra steps as outlined in the readme.

**Comment by CptMoore** [comment]
The installation documentation was revised several times over by now.
