### ISSUE TITLE
HOWTO: Logging Level for ModTek

### ISSUE THREAD

**Issue by XSNomad** [BattletechModders/ModTek#216]
In the battletech_log
- How to disable [TRACE] and [LOG] for ModTek Logs. and just leave it at [WARN] or [ERROR]

11:02:13.9267517 ModTek [TRACE] Log Level of logger name=BattleTech.Contract changed from level=null to level=ERROR(3)
11:02:13.9939614 ModTek [LOG] UILookAndColorConstants fields:245
11:02:15.6628365 ModTek [LOG] "Everyones Best Friend" 0.0.1.0
11:02:15.6638740 ModTek [LOG] 	Loaded assembly EBF (v1.0.0.0)
11:02:15.6639459 ModTek [LOG] 	Invoking 'EBF.Main.Init(String directory, String settingsJson)' using parameter dictionary

For Example, and thanks!

**Comment by XSNomad** [comment]
`        Trace = 200, // (extended) trace steps and variables, usually slows down the game considerably
        Debug = 210, // also used to trace steps and variables, but at a reduced rate to keep the logfiles readable and performance ok
        Log = 220, // minimal logs required to know what the user is doing in general, should have no impact on performance; user clicked x
        Warning = 230, // something wrong happened, but the mod will deal with it; a wrong config value, which has a safe fallback
        Error = 240, // something wrong happened, the mod might not work correctly going forward; an optional patch that didn't apply
        Fatal = 250, // (extended) something wrong happened, the the game is not usable anymore and needs to be shut down; missing basic settings
        OFF = 300 // (extended) useful to know how to disable logging for good`

**Comment by XSNomad** [comment]
`{
    "Logging": {
        "OverrideLoggerLevels": {
            "UnityLoggerName": "Error",
            "Debugger": "Error",
            "AppDomain": "Error",
            "ModTek": 230
        }
	}
}`

**Comment by CptMoore** [comment]
I've found a bug in the NullableLogger which didn't listen to changes, however Trace Logging should still be disabled by IsEnabledFor checks, meaning the bug from the issue might still be there

**Comment by CptMoore** [comment]
I've removed the OverrideLoggerLevels feature since it didn't properly work. If one wants to override log levels, one should just modify the HBS debug settings.json (e.g. via an advanced json merge or so)
