### ISSUE TITLE
SOME MODS DIDNT LOAD

### ISSUE THREAD

**Issue by M1ghty0bserver** [BattletechModders/ModTek#217]
Having a problem with the some BTA mods, now everytime I open the game I get "Some mods didn't load, chack mods\.modtek\ModTek.log" for more info. and then under that is "DZK RTD AND DP MECHS"

Im going to wipe and start the long AirSS process on adding each mod 1 by 1 until one of the mods re-bricks it, if anybody knows what happened befor i have to suffer again please let me know.

FYI, everything worked perfectly until i added the following mods in no particular order:
guns of kerensky BTE
SLDF Royal division
Timeline
MechResizer
Skirmish inventory unlock
JK rarity
SLDFitemsinshops4UW
SLDFitemsinshops4HM
SLDFiteminshops2campaignmechs
SLDFitemsinshops
RoyalMechAndStreaktoSLDFitemsinshops
JK variants2SLDFitemsinshops
HeatandWeight
00simconstants
JK BTMods
Weapon re-balance and buyable SLDF tech
Burstfire Autocannons
BetterReputationAlliance
SkillTreeRebuild
Expanded Arsenal
PermanentEvasion
2866
LogoReplacement
FHoSGear
BattletechPerformanceFix
BTA 3062 mini snub ppc
RoyalMechs
StreakMissileLaunchers
Enhanced Weapons 2 beta
FellofACargoShip
Special Equipment for Mechs
Sepecial Equipment in stores (yes the zip file is spelled wrong)
The Engine initiative
Sandman
A100N Parts
Salvage Ferro Plate
BetterTravelTimes
JumpJetsForAll
ZotsDifferentLosTechRewardsMechs
[DZK mods for BTA
Desuzakido BTA 3062 "these 2 didn't work so I uninstalled them so I don't think it could be them unless it overwrote something important"]
BTA 3062 clanner submod
Slime Specials
HYR-CAB 3025
Better Salvage

P.S. I want LAM's so if anybody knows what mod to DL and where they are on the star map please let me know. Thanks in advance.

**Comment by CptMoore** [comment]
you might want to look into .modtek/battletech_log.txt too or if mods have their own logs you need to check there too
