### ISSUE TITLE
Modtek 4.0 not working with newest HBS Battletech

### ISSUE THREAD

**Issue by Galahad0430** [BattletechModders/ModTek#222]
I followed the install instructions, but Modtek does not show up on the bottom of main screen. Where exactly should the Modtek folder be? In the same folder as Doorstop, or in the mods folder itself? I have tried it in both places and still nothing.

**Comment by CptMoore** [comment]
Mods folder, so unzipping ModTek should be it...
What OS (Windows XX, Linux .., MacOS)? What Gaming Platform(Steam, GOG, ..)?

**Comment by Galahad0430** [comment]
There are two Mods folders. 
![image](https://user-images.githubusercontent.com/131574247/233844486-1810b373-5161-47ab-a5cb-c0c293c40d4f.png)

And:
![image](https://user-images.githubusercontent.com/131574247/233844549-e497891e-d8ba-4b62-bade-eedf16a36da0.png)
 
 I use Steam on Windows 10

**Comment by CptMoore** [comment]
ah no, the winhttp.dll and all that stuff is supposed to be inside the BATTLETECH directory

so just unzip the zip directly into BATTLETECH dir, so that the mods dir in the zip appears as BATTLETECH/Mods

**Comment by Galahad0430** [comment]
That worked!!!  Thank you so much!
