### ISSUE TITLE
v4.0.0: JSON Merges involving tags do not work

### ISSUE THREAD

**Issue by korgano** [BattletechModders/ModTek#223]
ModTek v4.0.0+Branch.tags-v4.0.0.Sha.93e796e50038bfb92bdba80be4f0848d635ca4b3 (2023-03-17)
ProductName: BATTLETECH
ProductVersion: 1.9.1
Platform: GOG
BuildRevision: cdbbe62917b8c241c9d22c8540fee15595373c89
BuildBranch: live
BuildDate: 2020-02-26T08:21:38
BuildStamp: 200226-live-cdbbe62
BuildNumber: 686R

Intended Behavior:
JSON merge instruction `replace` targeting `PilotTags/items`, `ComponentTags/items`, etc... in the following format should generate a copy of the target JSON in the .modtek/cache directory with said changes:
```
{
    "TargetID": "pilot_d1_recruit",
    "Instructions": [
        {
            "JSONPath": "PilotTags/items",
            "Action": "Replace",
            "Value": [
                "pilot_npc_recruit",
                "pilot_npc_dynamic",
                "pilot_npc_d1",
                "base_skills_only"
            ]
        }
    ]
}
```

Actual behavior:
ModTek will **not** execute tag related JSON merge instructions and generate error messages regarding this:
```
23:35:28.7748785 ModTek [LOG] MergeCache: pilot_d1_recruit (PilotDef) missing in cache.
23:35:28.7767231 ModTek [WARNING] An instruction (Action: 'Replace' JSONPath: 'PilotTags/items') did not perform anything.

23:35:29.5068804 ModTek [LOG] MergeCache: Weapon_Narc_Standard_0-STOCK (WeaponDef) missing in cache.
23:35:29.5106671 ModTek [WARNING] An instruction (Action: 'Replace' JSONPath: 'ComponentTags/items') did not perform anything.
```

Other `replace` instructions that target a field **will** execute and generate changes in the cached JSON.

**Comment by CptMoore** [comment]
JSONPath syntax uses a dot, not a slash, to traverse properties

**Comment by korgano** [comment]
Then this is a documentation issue, as the example code in the [Advanced JSON Merging](https://github.com/BattletechModders/ModTek/blob/master/doc/ADVANCED_JSON_MERGING.md) page explicitly uses a slash to traverse the properties:

```
{
    "JSONPath": "MechTags/items",
    "Action": "Replace",
    "Value": [
        "unit_mech",
        "unit_heavy",
        "unit_role_brawler"
    ]
}
```
