### ISSUE TITLE
Modtek 4.2.0 not launching

### ISSUE THREAD

**Issue by RoskoDaneworth** [BattletechModders/ModTek#237]
System Win10 latest

Steam Game file integrity checked. All DLCs present.

Modtek 4.2.0 fails with error. Dont know what to do and how to fix. Previous versions not tried yet.

> 22:03:45.582 Preloader v4.2.0+Branch.tags-v4.2.0.Sha.17114d0f2c5e8dc838c6d947e6d5646cfe9777d6 (2024-06-13)
> 22:03:45.599 GameMainAssemblyFile: H:\SteamLibrary\steamapps\common\BATTLETECH\BattleTech_Data\Managed\Assembly-CSharp.dll
> 22:03:45.599 ModTekDirectory: H:\SteamLibrary\steamapps\common\BATTLETECH\Mods\ModTek
> 22:03:45.601 SingleInstanceEnforcer [pid=59884]: Locking
> 22:03:45.602 SingleInstanceEnforcer [pid=59884]: Locked
> 22:03:45.602 Find backups, restore assemblies and remove backups.
> 22:03:45.685 Assembly `BATTLETECH/BattleTech_Data/Managed/Assembly-CSharp.dll` contains no known injections.
> 22:03:45.686 Cleaning up obsolete files.
> 22:03:45.703 Exiting the game, preloader failed: System.UnauthorizedAccessException: Access to the path "H:\SteamLibrary\steamapps\common\BATTLETECH\BattleTech_Data\Managed/Mono.Cecil.dll" is denied.
>   at System.IO.File.Delete (System.String path) [0x00073] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 
>   at ModTek.Preloader.Loader.Cleaner.CleanupObsoleteFiles () [0x00041] in <041acef2000e455683e9b0b0dae874da>:0 
>   at ModTek.Preloader.Loader.Cleaner.Clean () [0x00005] in <041acef2000e455683e9b0b0dae874da>:0 
>   at ModTek.Preloader.Loader.Preloader.Run () [0x00061] in <041acef2000e455683e9b0b0dae874da>:0 
>   at Doorstop.Entrypoint.Start () [0x00000] in <041acef2000e455683e9b0b0dae874da>:0 
> 22:03:45.707 SingleInstanceEnforcer [pid=59884]: Unlocking
> 22:03:45.707 SingleInstanceEnforcer [pid=59884]: Unlocked

**Comment by CptMoore** [comment]
I don't understand, Managed/ should not contain a Mono.Cecil.dll

If you do find mono.cecil.dll in that directory it claims, can you please delete the whole Managed/ directory and then do a file integrity check?

**Comment by RoskoDaneworth** [comment]
> I don't understand, Managed/ should not contain a Mono.Cecil.dll
> 
> If you do find mono.cecil.dll in that directory it claims, can you please delete the whole Managed/ directory and then do a file integrity check?

Problem solved, it is because of BTML that was installed since some mods on nexus were asking it. Didnt know it was incompatible with modtek v3+ (v2 working okay).
