### ISSUE TITLE
Give compatibility hints to users and mod authors

### ISSUE THREAD

**Issue by thokari** [BattletechModders/ModTek#32]
Hi, great project you have here!

When I was thinking myself about the problem of keeping mods up to date and merge them...
Specifically, how to quickly get an overview about which JSON values are touched by various mods, in order to notice conflicts.
ModTek would be a good place to put code like that, as it aims to solve the general problem also.

I think it could be helpful to keep track of which files / JSON values are touched by which mod during the merging process, and if a value is changed the second time, create a warning message, that mentions both mods and the key / value they want to change.

That could give both users and authors a hint which mod they prefer to load later, or to figure out when to put something in the "conflicts_with" property.

Of course this does not apply to mods that change code...

**Comment by Mpstark** [comment]
Yeah, definitely want to have as much helpful logging as possible. Doing a intersect between mods is a good idea, to see if mods touch the same pieces of a file.

**Comment by Mpstark** [comment]
I've added a harmony summary to help diagnose compatibility errors stemming from patching the same methods. Also, the merge_cache file should be somewhat helpful in determining if multiple mods are patching the same json files.

I hope to add more later.

**Comment by Mpstark** [comment]
I believe that we're as far along this path as we can be -- doing an intersect between JSON merges would probably be too expensive.
