### ISSUE TITLE
Document list of manifest entry types

### ISSUE THREAD

**Issue by allquixotic** [BattletechModders/ModTek#55]
In my mod.json I have:

```
	"Manifest": [
		{ "Type": "MechDef", "Path": "IndartMech\\mechdef_indart_ID-X.json" },
		{ "Type": "ChassisDef", "Path": "IndartMech\\chassisdef_indart_ID-X.json" },
		{ "Type": "HardpointDataDef", "Path": "IndartMech\\hardpointdatadef_indart.json" },
		{ "Type": "MoveDef", "Path": "IndartMech\\movedef_indart_ID-X.json" }
	]
```

In output_log.txt I'm getting:

```
Non platform assembly: C:\Program Files (x86)\Steam\steamapps\common\BATTLETECH\Mods\ModTek.dll (this message is harmless)
Unloading 5 Unused Serialized files (Serialized files now loaded: 1)
ArgumentException: The requested value 'MoveDef' was not found.
at System.Enum.Parse (System.Type,string,bool) <0x005cb>
at System.Enum.Parse (System.Type,string) <0x00027>
at BattleTech.BattleTechResourceLocator.RefreshTypedEntries () <0x00103>
at BattleTech.BattleTechResourceLocator..ctor () <0x00076>
at (wrapper dynamic-method) BattleTech.Data.DataManager..ctor_Patch1 (object,MessageCenter) <0x001a6>
at BattleTech.GameInstance..ctor () <0x00161>
at BattleTech.UnityGameInstance.Reset () <0x0008a>
at BattleTech.UnityGameInstance.Awake () <0x00120>
```

I'd prefer not to have to play a guessing game to figure out the correct "Type" to assign to the new items in the manifest. Further:

 - The types don't correspond exactly to the folder names. If they did, the "MechDef" -- which is given in many examples in the docs -- would be labeled "mech", and "ChassisDef" would be "chassis". 
 - The types don't correspond to a CamelCased version of the prefix of the file name. If they did, "movedef_xxx.json" would correspond to a type of "MoveDef", but it says that type isn't found.

So how do I know what type it *is*, and can we get a complete list of all possible options?

**Comment by CptMoore** [comment]
look in the original VersionManifest.csv for the types, there you can see MovementCapabilitiesDef

**Comment by Mpstark** [comment]
I can see how that'd be frustrating, as @CptMoore has said, `MoveDef` is actually called `MovementCapabilitiesDef`, these types are gotten from the `VersionManifest.csv` and translate to an enum in game code.

I'll look into getting them parsed out and added to the wiki.

**Comment by CptMoore** [comment]
since the values themselves say nothing we would still need something that links values and meaning. only the manifest does that for now
