### ISSUE TITLE
Support Soundbank Replacement/Addition

### ISSUE THREAD

**Issue by gnivler** [BattletechModders/ModTek#60]
Hi.  I looked through open and closed issues and didn't see this, sorry if it's in an FAQ somewhere I missed.

Just trying to replace the soundbank .bnk files for some basic mods.  Per the docs I thought I'd just have to create the proper path at root of the mod, putting my copy of the mechs.bnk file at the mirrored path.  It just doen't seem to actually work (the vanilla bnk is used).

_The "Manifest" entry here is of particular note, as this will load files into the VersionManifest at load. By default, ModTek assumes that files in \MyModDirectory\StreamingAssets\ are mirrors of base game files in contained in \BattleTech_Data\StreamingAssets\ and will load those files without needing to be told about them._

    BATTLETECH\Mods\mymod\StreamingAssets\Audio\GeneratedSoundBanks\Windows\mechs.bnk

This is the only thing that looks like it might be a problem in the ModTek log:

    Could not find an existing VersionManifest entry for mechs.bnk. Is this supposed to be a new entry? Don't put new entries in StreamingAssets!

edit, very simple `mod.json`

    {
        "Name": "MyMod",
        "Version": "1.0",
        "Enabled": true,
    }

Thanks for your time.

**Comment by Mpstark** [comment]
This is in PR #127 -- at least replacing them
