### ISSUE TITLE
Allow mods to write to ModTek log

### ISSUE THREAD

**Issue by Sheep-y** [BattletechModders/ModTek#74]
In [my mod](https://github.com/Sheep-y/BattleTech_Mods/tree/master/AttackImprovementMod/src) I logs info like settings, patched methods, or errors thrown into a custom log file that is mod specific.

Can we borrow ModTek's Logger?  Things like Exception dump is perhaps better logged with ModTek so that all errors are in one place.  If you add log level and lazy string format I'll happily migrate all the logging over too!

**Comment by CptMoore** [comment]
You can use the game's logger to reuse the central logfile. I do it for all my mods.

var logger = HBS.Logging.Logger.GetLogger(Name)
logger.Log("hello world");

BATTLETECH\BattleTech_Data\output_log.txt

**Comment by Sheep-y** [comment]
But does ModTek use it?  Isn't it better to keep game log to game and mod to mod log in mod folder?

**Comment by CptMoore** [comment]
If mod has uncatched exceptions those can appear in game log anyway... So best put everything there to be sure.

**Comment by Sheep-y** [comment]
Ah. I see. So that is where uncaught exception goes. I just catch almost everything so that my mod have a less chance to break the game when it fails (eventually). Yes. Redirecting to game log seems to be a very good idea.

@Mpstark I still wish the Logger can be made public if only to offer more options, but it you don't wish that you may close this ticket.
