### ISSUE TITLE
Allow mod to get mod list

### ISSUE THREAD

**Issue by Sheep-y** [BattletechModders/ModTek#75]
I have a mod that is doing lots of little things, some simpler than others and some more flexible than others.

Example: my mod can tune roll correction strength, and by default half its correction. It is flexible but conflicts with a mod that specifically disables roll correction.

So what I would like to do is if I can get a list of mods, when it is my turn to load, I can selectively disable features if I see a known mod. I can actually skip patching those methods.

Maybe a base mod class can be created for mods to extends from, who can then use methods to talk to MotTek?  Existing mods does not need to be modified, and new methods can be added in future without breaking mods.

**Comment by CptMoore** [comment]
An "optional dependsOn" that would allow a mod to be loaded after another mod but if it doesnt exists still loads the mod with the optional dependency.

Alternatively a second callback method thats called after the loadorder has been executed, and everything is loaded up.

**Comment by Sheep-y** [comment]
Ah, didn't know ModTek dependency actually mean "LoadMeAfter" instead.

But I don't mind the load orders. I want to know whether some specific mods would be loaded too, so that my mod can change its settings and behaviour.

I haven't tried yet, but the alternative seems to be to defer my patching and then use reflection or harmony to test those mods.  Doable, but if we have that list then I don't need to defer or reflect.

**Comment by Mpstark** [comment]
Is this something that we still would want? We could change `modLoadOrder` accessibility to `public`, but mods that used this would have to have a reference to ModTek, which I personally don't think is a great idea.
