### ISSUE TITLE
Path not found in mod.json when processing manifest on MacOS when '\\' is used

### ISSUE THREAD

**Issue by nullify005** [BattletechModders/ModTek#76]
So I've been having a crack at using JK_Variants on MacOS & noticed that any time the mod.json mentions a path with a trailing double backslash the entry cannot be processed & the logging line https://github.com/Mpstark/ModTek/blob/master/ModTek/ModTek.cs#L283 is output.

If the double backslash is removed then the manifest entries are loaded correctly.

Would it be too much trouble to have some code which respects the path separator between the two operating systems which Battletech runs on?

While in Windows a '\\' might be considered fine, this isn't something which will work on MacOS / Unix. I recall that Windows can be made to respect the forward slash instead as the path sep?

In order to retain compatibility with the mods already out there which are using the examples in the mod.json, perhaps a regex to replace '\\' with '/' if we detect that it's Darwin instead of Windows?

**Comment by esotericist** [comment]
Windows API calls do in fact work just fine with `/` instead of `\`, and for cross-platform code there's (usually) no reason not to use `/`. The only exception I'm aware of is a handful of legacy windows console applications, which shouldn't be pertinent here?
