### ISSUE TITLE
ModTek does not work with 1.3/Flashpoint

### ISSUE THREAD

**Issue by jegelstaff** [BattletechModders/ModTek#81]
When I try to inject it with the latest version of the game, I get a lot of errors in the command prompt window. I assume it needs updating for 1.3/Flashpoint and this is a known issue? Is it being worked on?
Thanks for all your work!
--Julian

**Comment by CptMoore** [comment]
mpstark is MIA

janxious has taken the time to update the mod tools
https://github.com/janxious/BattleTechModLoader
https://github.com/janxious/ModTek
