### ISSUE TITLE
versioning mismatch v0.4.2

### ISSUE THREAD

**Issue by DainUnicorn** [BattletechModders/ModTek#94]
The [v0.4.2 release](https://github.com/BattletechModders/ModTek/releases/tag/v0.4.2) reports "ModTek v0.4.0.19688" on its splash pop-up, the version display on the Main Menu footer, and in log files.

This might confuse someone into thinking they have an out-of-date version.

**Comment by Mpstark** [comment]
I'm closing this issue, because it deals with a release that's already out in the wild.
