### ISSUE TITLE
Automated versioning for dll

### ISSUE THREAD

**Issue by CptMoore** [BattletechModders/ModTek#96]
For MechEngineer, I use GitVersionTask to do automated assemblyinfo versioning as part of building. Just tag the HEAD and rebuild the dll. Works great, could quickly port it to ModTek.

**Comment by CptMoore** [comment]
I've tested GitVersionTask on Linux and its currently buggy

hopefully https://github.com/GitTools/GitVersion/issues/1511 will fix it

until then I'm hesitant to put it in ModTek, do we only use Windows for releases?

**Comment by janxious** [comment]
I don't know what @Mpstark uses, but I was building MT on MacOS for the last half year.

**Comment by janxious** [comment]
This seems like on *nix it could be solved with a small git commit hook and regex. I suspect powershell can do it easily, too, but I don't know anything about that.

**Comment by CptMoore** [comment]
I rather wait for GitVersionTask to be fixed, it also does smart increments, e.g. if you have 1.0.3 tagged, but have untagged commits afterwards on your current branch, it will compile as 1.0.4. It is the ultimate tool for building these things. Issue is that GitVersionTask isnt using the git nuget package, but packaging libgit itself. That will hopefully change soon.

In any case, I'll create a PR for @janxious to test on mac!

**Comment by CptMoore** [comment]
@jo @Mpstark https://github.com/orgs/BattletechModders/teams/btml-modtek does not have access to ModTek, couldnt push my branch :(
