### ISSUE TITLE
linux, mod.json and trailing slash in directory path

### ISSUE THREAD

**Issue by sozforex** [BattletechModders/ModTek#97]
On linux (and likely OSX) ModTek will not find directory inside specific mod, if path to this directory in mod.json ends with double slash ("\\\\").
```
    "Manifest": [
        { "Type": "WeaponDef", "Path": "SubFolder\\SubSubFolder\\" },
    ],
```
On linux ModTek will search inside "SubFolder" for directory with name "SubSubFolder\\" (single slash, "\\" - allowed character in file/directory name on linux), while mod author meant it to be just "SubSubFolder".
It would be awesome, if ModTek just stripped trailing slash, or at least it was suggested to modders in README.md to not to add trailing slashes to directory paths.
Thanks.

**Comment by CptMoore** [comment]
I might have reintroduced linux bugs with #191, just reopen or open new issues
