### ISSUE TITLE
Support standalone zipped mod collections

### ISSUE THREAD

**Issue by CptMoore** [BattletechModders/ModTek#98]
basically its for RT. kinda lots of requirements.

Features:
- make sure its immutable
- make sure its only one file, use zip as that's a nice standard (encrypted zip support requested by Lady)
- ignore all other mods except the ones in the zip (how to set that up?)
- include the .modtek cache (to avoid having to rebuild everything on first load, but maybe thats unnecessary)
- active mods list in the zip should be done outside of the zip (which are active/inactive), maybe also give the loadorder list? to allow a setup script to define optionality

what probably should be solved/checked as part of it
- does zipping help loading performance or hurt?
- what happens with settings etc? do we need https://github.com/BattletechModders/ModTek/pull/69 first?
- should there be a compile step for the zip or just zip the current Mods directory and that already would be a fully working mod compilation?
- how to allow optionality? allow several zips?
- etc..

**Comment by LadyAlekto** [comment]
dependancy check per zip would be nice too, for optional parts being kept together

**Comment by CptMoore** [comment]
performance improvements are not there
and its too late to introduce it now to make installs more clean
also the community for big mods has switched to git checkout based launchers to fix any consistency issues
