### ISSUE TITLE
AdvancedJSONMerges -- Support merging into mod files as well

### ISSUE THREAD

**Issue by Mpstark** [BattletechModders/ModTek#99]
Currently everything assumes that we're merging into files from StreamingAssets, if we changed that to be relative to the game directory, and changed the type fetching, we could support advanced json merges into mod files as well.

This would break any mods that currently use this, as they would need to be updated to support the fact that the path has changed.

@CptMoore : is this something that we want to do before releasing 0.5.0? 0.4.2 doesn't include this functionality -- so it might be the best time to introduce breaking features. I know someone said something about there being some sort of unofficial 0.4.3

**Comment by CptMoore** [comment]
yea it would be helpful, I tried to do 
```        internal static string ResolvePath(string path, string rootPathToUse)```

```{{Mods}}/somemod/modfile.json``` would have related to a mod file, but dont think I tested that ever.

Isn't something like that missing for normal merges too?

I still dont understand the inferID vs path relationship fully.

**Comment by Mpstark** [comment]
Normal merges work fine for merging onto mod content (you can see [code for that here](https://github.com/BattletechModders/ModTek/blob/master/ModTek/ModTek.cs#L956)). JK uses this for his mods, so I'm pretty certain it works.

I've changed the advanced merge thing to support this functionality as well, which was just a simple matter of changing the root folder. I've also removed the {{Mods}} thing since it isn't necessary anymore. This is in commit b7a3729c1eeec6337fefb9f7717f3b05beb89b27

As to the inferID vs. path thing -- inferID reads json files for the ID as opposed to assuming it based on the filename. This is a "more correct" type of thing, as almost all vanilla files use the ID as the file name excluding the extension.

**Comment by Mpstark** [comment]
Would you mind testing advanced JSON merges again with these changes? I still don't have a test case. Remember that you'll need to change the TargetFile attribute to reflect the new root path, i.e. add `BattleTech_Data/StreamingAssets/` or whatever.

This is the last thing I think before releasing 0.5.0.

**Comment by Mpstark** [comment]
I decided to stop being lazy and test it myself.

```json
{
    "TargetFile": "BattleTech_Data/StreamingAssets/data/behaviorVariables/global.json",
    "Instructions": [
        {
            "JSONPath": "$..behaviorVariables[?(@.k == 'Float_ExistingTargetDamageForOverheatAttack')]",
            "Action": "Replace",
            "Value": {
                "k": "Float_ExistingTargetDamageForOverheatAttack",
                "v": {
                    "type": "Float",
                    "floatVal": 180
                }
            }
        }
    ]
}
```

Works as expected.

**Comment by Mpstark** [comment]
```json
{
    "TargetFile": "Mods/JK_VariantsCampaign/mech/mechdef_shadowhawk_SHD-2K.json",
    "Instructions": [
        {
            "JSONPath": "$..MechTags.items",
            "Action": "ArrayConcat",
            "Value": [
                "unit_DEVTEST"
            ]
        }
    ]
}
```

Did *not* work as expected. My assumption that new entries were added to the cache was incorrect, and I fixed the issue. Interestingly, the issue was harder to diagnose because of the progress bar code, I'll open another issue for that.

Once I fixed the type thing, it worked as expected.

**Comment by Mpstark** [comment]
I'm going to mark this as closed as this is now working.
